name: CheckPRLinks
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  CheckPRLinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn
      - name: Run Build
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Run Server
        run: |
          node ./node_modules/.bin/serve client/www/next-build --no-request-logging &
          sleep 5
      - name: Run Link Checker
        id: checkLinks
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          result-encoding: string
          script: |
            const { checkDevLinks } = require('./tasks/link-checker.js');
            return await checkDevLinks();
      - name: Fail if broken links have been found
        if: ${{ steps.checkLinks.outputs.result }}
        run: exit 1
